### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by jerrygreen** [azer/indexeddb#2]
The readme looks promising, especially the sync part (how granular is it, btw?). I think I'm going to try this thing.

But the main idea here: why not publish this to npm?

**Comment by azer** [comment]
Hi Jerry,

I decided to not publish any of my work in NPM about 4 years ago. 
https://kodfabrik.com/journal/i-ve-just-liberated-my-modules

But you could actually publish it there. I don't even have an NPM user anymore :) I'm happy to accept your patches as well.

Thanks

**Comment by jerrygreen** [comment]
@azer oh... Actually, I kinda hate npm too. Even [author of NodeJS does kinda hates npm](https://youtu.be/M3BM9TB-8yA?t=584). Though, I'm not sure if the same thing won't ever happen for github...

But anyway my only worry here is probably different than just using npm. It's about versioning. For example, by running something like this: `yarn add packagename` I'll get something like this, in my `package.json`:

```
"packagename": "0.2.7",
```

I.e. package name, and the current latest version's digits. But when I do `yarn add authorname/packagename`, I'll get something like this:

```
"packagename": "authorname/packagename",
```

Which is nonsense. No version. When the package will be updated, it may be accidentally updated in the project, which leads to problems with having some working sets of libraries. Yes, - there's `yarn.lock`, listing a concrete commit anyway, but it's more like a cache rather than single source of truth, because sometimes it gets conflicts, is deleted, and recreated.

It's still possible to manually set it up in `package.json`:

```
"packagename": "authorname/packagename#a364c48",
```

But it has some commit hash, not a version, which is not very descriptive, though it's solves the problem.

So maybe I can't argue to using npm, but would you like to start at least `0.1.0` version (or even `0.0.1`), and set a tag to this latest commit? So it will be possible to do this:

```
"packagename": "authorname/packagename#0.1.0",
```

or

```
"indexeddb": "azer/indexeddb#0.1.0",
```

rather than just:

```
"indexeddb": "azer/indexeddb",
```

And maybe I can even assure you to use this semantic versioning for all your libraries? It has nothing to do with npm, but it's still a useful practice. I'm not sure if git tags are transferred within PRs, but I'll make a PR to check it out.

Thanks for your reply, and thanks for listening! You look like a real cool guy, I've subscribed to your blog like a day ago, when found your lib.
